# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

browser_mod:
  prefix: "browser_"
  devices: 
    20225ac3-c0a954df:
      name: tompc

history:
  exclude:
    domains:
      - binary_sensor

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_clientsecret

homeassistant:
  packages: !include_dir_named include

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: FrontEnd
      icon: mdi:script
      show_in_sidebar: true
      filename: ui-lovelace.yaml
