# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

browser_mod:
  prefix: "browser_"

history:
  exclude:
    domains:
      - binary_sensor

homeassistant:
  packages: !include_dir_named include

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Dashboard
      icon: mdi:home
      show_in_sidebar: true
      filename: ui-lovelace.yaml
