- platform: group
  name: TV Corner
  entities:
    - light.tvcorner1
    - light.tvcorner2
    - light.tvcorner3

- platform: group
  name: Toilet Upstairs
  entities:
    - light.toilet_first_floor_1
    - light.toilet_first_floor_2

- platform: group
  name: Garage
  entities:
    - light.garage_back_light
    - light.garage_front_light

- platform: group
  name: Front Living Room
  entities:
    - light.tv_corner
    - light.reading_corner

- platform: group
  name: Back Living Room
  entities:
    - light.dinner_table
    - light.pc_corner

- platform: group
  name: Living Room
  entities:
    - light.front_living_room
    - light.back_living_room

- platform: group
  name: Master Bedroom
  entities:
    - light.bed_side_lamp_1
    - light.bed_side_lamp_2
    - light.bedroom_light