button_card_templates: !include_dir_merge_named ui/card_templates

views:
  - !include ui/ui-overview.yaml
  - !include ui/ui-groundfloor.yaml
  - !include ui/ui-firstfloor.yaml
  - !include ui/ui-secondfloor.yaml
  - !include ui/ui-outside.yaml
  - !include ui/ui-power.yaml
  - !include ui/ui-system.yaml
  - !include ui/experimental.yaml
