base:
  aspect_ratio: 1/1
  show_state: false
  show_icon: false
  state:
    - value: 'on'
      styles:
        card: [background-color: 'rgba(255, 255, 255, 0.8)']
        name: [color: 'rgba(0, 0, 0, 0.6)']
        state: [color: 'rgba(0, 0, 0, 0.6)']
  tap_action:
    action: toggle
    haptic: light
  styles:
    name:
      [top: 80%, 
       left: 5%, 
       line-height: 1vw, 
       position: absolute
      ]
    state:
      [top: 40%, 
       left: 0%, 
       line-height: 1vw, 
       position: absolute
      ]
    card:
      [font-family: Sf Display,
       letter-spacing: 0.05vw, 
       font-weight: 400, 
       color: 'rgba(255, 255, 255, 0.3)', 
       font-size: 0.8vw,
       background-color: 'rgba(115, 115, 115, 0.2)',
       border-radius: 0.8vw,
       box-shadow: none,
       transition: none
      ]
    custom_fields:
      circle:
        [
          top: 8.5%,
          left: 56.2%,
          width: 3.5vw,
          position: absolute,
          letter-spacing: 0.03vw
        ]