settings:
  variables:
    #     entity_tablet: switch.galaxy_tab_a_screensaver
    #     entity_browser_mod: media_player.browser_9c06ce87_d1cf313c

    translate_unknown: Unknown
    translate_idle: Inactive
#     translate_home: Ja
#     translate_not_home: Nej
